[package]
name = "work-break"
version = "0.7.2"
edition = "2021"
description = "Work-break balancer for Windows / MacOS / Linux desktops"
license = "MIT"
repository = "https://github.com/ShadoySV/work-break"
keywords = ["productivity", "app", "cross-platform", "time-tracker"]

build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
confy = "2"
serde = { version = "1", features = ["derive"] }
chrono = "0.4"
interprocess = "2"
ron = "0.12"
ctrlc = { version = "3.5", features = ["termination"] }

[target.'cfg(target_os = "macos")'.dependencies]
mac-notification-sys = "0.6"

[target.'cfg(not(target_os = "macos"))'.dependencies]
notify-rust = "4.18"

[target.'cfg(windows)'.build-dependencies]
embed-resource = "3"
